### ISSUE TITLE
FEAT-fontsize

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#103]
**Is your feature request related to a problem? Please describe.**
Would like to be able to change the font size.

**Describe the solution you'd like**
Change font size in settings page.

**Additional context**
[Source](https://discordapp.com/channels/691409213653778444/723780579903930389/737119187473924097)

**Comment by Jemoka** [comment]
@zbuster05 and the #55 crew, you are hereby called upon!

**Comment by Jemoka** [comment]
cmd +?
