### ISSUE TITLE
BUG: Mac version very slow and doesn't handle dates

### ISSUE THREAD

**Issue by cstott** [Shabang-Systems/Condution#106]
Hi,

Just downloaded the app - it looks interesting. Once I entered my information it seemed to just sit there (at least 10 minutes). I did a refresh and it brought up the main window. I tried to click on the Project + and it seemed to take at least 30 seconds to respond (of course I had hit it a couple of times so it added a bunch of unnamed projects). I tried creating a project and when I entered in the tasks (again after a long response) it allowed me to enter the information. When I went back to look at that same task the Start/End times were set to my current time.

It looks good but is the Mac version a little behind?

Thanks

Running OSX 10.15.6 on a Mac Mini

**Comment by Jemoka** [comment]
Hey there 👋 
Sorry about this! I believe this is due to the fact our servers was crashing Sunday night due to the sudden increase in users. I think that should be fixed as they are now fed.
Please try restarting the app again and see if the issue still persists. If not, feel free to close this issue.

**Comment by cstott** [comment]
Hi,
That appears to fix the performance issue (likely the "reddit affect"). We can close this ticket.

There still seems to be some issues with the dates. This is similar to issue #126 

Thanks,
Chris

**Comment by Jemoka** [comment]
Thanks so much for your patience! We will address #126 there. Thanks so much!

**Comment by Jemoka** [comment]
Ok discussion merged to #141
