### ISSUE TITLE
FEAT-task-title-placeholder

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#111]
**Is your feature request related to a problem? Please describe.**
Placeholder for tag title, just like the description.

**Additional context**
[Discord source](https://discordapp.com/channels/691409213653778444/723796928739016704/737198752477216779)

**Comment by Jemoka** [comment]
not sure what this means, but ok

**Comment by Exr0n** [comment]
Like there should be a little gray text that is the placeholder for the title of a newly created task.
