### ISSUE TITLE
FEAT Better Upcoming

### ISSUE THREAD

**Issue by Ban-Ironic-Ohms** [Shabang-Systems/Condution#117]
**Is your feature request related to a problem? Please describe.**
Be able to see upcoming out further (30 days)

**Comment by richardfeynmanrocks** [comment]
Just curious, is there a specific reason this is `dreams-and-wishes`? Is there something about the backend that makes this especially difficult?

**Comment by Jemoka** [comment]
The layout would be hard... dreams-and-wishes is just our "this is not assigned to a particular milestone" bucket

**Comment by Jemoka** [comment]
Done.
