### ISSUE TITLE
BUG-weird-sameday-defer

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#118]
**Describe the bug**
"Same-day defer dates behave weirdly (i.e. tasks with them don't grey out when I set it to later in the day, and sometimes stay greyed out when I set it back to earlier today)."

**To Reproduce**
1. Create a task
2. Change defer date to be today

**Expected behavior**
Gray out based on time stamp relative to current time.

**Desktop (please complete the following information):**
- OS: MacOS 10.13.6
- Version: beta-v0.2.3_build1_M

**Additional context**
[Discord source](https://discordapp.com/channels/691409213653778444/723780625097556029/737342398044045322)

**Comment by richardfeynmanrocks** [comment]
> OS: MacOS 10.15
Version: Unkown, contact quantumish#3800

@Exr0n 
OS: MacOS 10.13.6
Version: beta-v0.2.3_build1_M 
(which is to my knowledge the most recent release as I have not been prompted to update)

**Comment by Exr0n** [comment]
Thanks, updated.
