### ISSUE TITLE
BUG-daterow-ignores-inbox

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#119]
**Describe the bug**
The daterow ignores unsorted tasks with due dates.

**To Reproduce**
1. Go to 'Upcoming'
2. Add something to inbox!
3. Change due date to sometime this week

**Expected behavior**
Number in daterow changes to account for unsorted tasks in the inbox

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Condution
 - Version: Beta-v0.2.3_build1M

**Additional context**
[Discord source](https://discordapp.com/channels/691409213653778444/723780625097556029/737403139644325990)

**Comment by Jemoka** [comment]
#FeatureNotABug #Wontfix

**Comment by Exr0n** [comment]
Wait @Jemoka can we change this? Or do you want me to make a feature request?

**Comment by Jemoka** [comment]
So does it showing up on the datebar make more sense? I did this to encourage people to sort their freaking inboxes.

**Comment by Exr0n** [comment]
Because some of us don't use the GTD system strictly. We're a productivity app with GTD flavors, not a GTD app. I can find textual evidence for this if needed.

Anyways, if somebody spent the time to put a date on a task the app should respect that.

**Comment by Jemoka** [comment]
Ah, using my word against myself. I see. 

Ok then

**Comment by Exr0n** [comment]
😎

**Comment by richardfeynmanrocks** [comment]
> I did this to encourage people to sort their freaking inboxes.
Wait I'm genuinely confused. Is there any way to sort one's inbox (or get a task out of the "unsorted" state) besides placing it in a project? What about tasks that aren't in a specific project?

**Comment by Jemoka** [comment]
In OF/GTD style, things must be in projects.

**Comment by Jemoka** [comment]
Granted, OF also allow you to optionally set inbox to clear with a due date. Let me know if you want this feature.

**Comment by richardfeynmanrocks** [comment]
I don't know — but I feel as if certain tasks just are inherently not part of a project (one-off tasks, small chores, etc). 

OF had single-action lists (or something like that, I don't fully remember) to sort of get around some of those inherent problems but that solution always felt awkward, although it did help. Condution may benefit with the inclusion something similar.

**Comment by Jemoka** [comment]
so if I am understanding correctly, the feature requested is separating unsorted from the inbox?

**Comment by richardfeynmanrocks** [comment]
The feature request is that there should be some method of assigning due dates to tasks that are not part of any project and won't be part of any project. Whether that is done through the inbox or some other way (the benefit here I assume is that the inbox stays "purer" in the GTD context), I just think this functionality should exist and having due dates not appear is a little annoying.

**Comment by Exr0n** [comment]
So basically, there would be no problem if we just made tasks in the inbox with due dates appear in the daterow. Right?

**Comment by Jemoka** [comment]
> assigning due dates to tasks

I mean you _can_ assign due dates to tasks in the inbox, it's just not added to the daterow count. So then #119 would solve the issue if I am understanding you correctly.

**Comment by richardfeynmanrocks** [comment]
Yes, [#119](https://github.com/Shabang-Systems/Condution/issues/119) would work just fine.

**Comment by Jemoka** [comment]
Ok. Excellent. We will try to get this out sometime in the next few updates.

**Comment by Jemoka** [comment]
This was fixed a long time ago.
