### ISSUE TITLE
BUG 'Due soon' in Completed

### ISSUE THREAD

**Issue by richardfeynmanrocks** [Shabang-Systems/Condution#125]
**Describe the bug**
Checkboxes appear red in Completed. While not serious, it is a little silly.

**To Reproduce**
1. Set a task to be due tomorrow.
2. Complete it.
3. Go to "Completed".
4. Notice that the task is still orange. Oh no! 

**Expected behavior**
Task reverts back to normal color in Completed as it's... well, *completed*.

**Desktop (please complete the following information):**
 - OS: Shouldn't really matter, but OSX 10.13
 - Version: beta-v0.2.3_build1_M

**Comment by Exr0n** [comment]
@richardfeynmanrocks should we make them all gray or archive the color when it was completed?

**Comment by richardfeynmanrocks** [comment]
I think making them gray would make the most sense as completed tasks can't be due soon (also for you can just compare their due date to their completion time to get how close it was instead of keeping the color).

**Comment by Jemoka** [comment]
Feature and not bug. Not closing in favor of further discussion.

**Comment by richardfeynmanrocks** [comment]
How is this a feature? The color progresses and everything in Completed looks as if its overdue.

**Comment by Jemoka** [comment]
I mean if you have a due date on every task everything in completed should be not due yet (good job, you are ahead), due soon (good job, you are on schedule), overdue (well, that's normal too.) No?

**Comment by Exr0n** [comment]
But long running tasks shouldn’t change, like it shouldn’t say “oh no, you were late on this thing” when you actually weren’t.

**Comment by Jemoka** [comment]
k then. I will take a look and triage.

**Comment by Jemoka** [comment]
Not anymore!
