### ISSUE TITLE
BUG Inconsistent Due Times

### ISSUE THREAD

**Issue by richardfeynmanrocks** [Shabang-Systems/Condution#126]
**Describe the bug**
Due times require some persistence to be set correctly.

**To Reproduce**
1. Make a new task.
2. Set a due date for another day at 1:23 PM
3. Click away to another perspective
4. Click back and notice how the due time reset to 12:00 AM

**Expected behavior**
Due dates should not change as soon as I turn my back on them.

**Desktop (please complete the following information):**
 - OS: MacOS X 10.13.6
 - Version: beta-v0.2.3_build1_M

**Comment by Ban-Ironic-Ohms** [comment]
This may be an issue of you not pressing enter, or saving the time? Could you double check @richardfeynmanrocks

**Comment by richardfeynmanrocks** [comment]
Alright I messed with it some more and I discovered that the issue lay in the little field in the bottom of the calendar:
<img width="189" alt="Screen Shot 2020-07-28 at 10 03 09 AM" src="https://user-images.githubusercontent.com/16178246/88697570-a12f9a00-d0b9-11ea-8766-40a09380439d.png">
Typing a value here and pressing enter does not actually set the value.

**Comment by Jemoka** [comment]
All of this should be in some way addressed (partially) by #136. Mayybe

**Comment by Jemoka** [comment]
Closing in favor of #141
