### ISSUE TITLE
FEAT-tooltips

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#128]
**Is your feature request related to a problem? Please describe.**
Hover tooltips for confusing buttons (flag, globe, repeat). 

**Additional context**
[Discord source CIPHER73#4789](https://discordapp.com/channels/691409213653778444/723796928739016704/737560465516920862)

**Comment by Jemoka** [comment]
Humph duplicate of #47, but it never got merged, it seemed. Will investigate, but closing this one now.
