### ISSUE TITLE
BUG Increase button size

### ISSUE THREAD

**Issue by EricChen1248** [Shabang-Systems/Condution#129]
**Is your feature request related to a problem? Please describe.**
Several buttons are way too small, mostly the "add" and "x" buttons, but I feel like many of the others should also be increased in size.

**Describe the solution you'd like**
Increase the button size, or at the very least the bounding box for the click event. See image, even mouse cursor in this area doesn't register as clicking the x button
![image](https://user-images.githubusercontent.com/19816842/88645101-541de900-d0f6-11ea-8625-c06dcfeff71b.png)

The x button here is also tremendously tiny.
![image](https://user-images.githubusercontent.com/19816842/88645194-6ef05d80-d0f6-11ea-8cd2-a9c17d55f755.png)

Issue is even more prominent on smaller screens, where my fat fingers just can't hit the right thing

**Additional context**

**Comment by Ban-Ironic-Ohms** [comment]
@EricChen1248, working in it now, anything else in particular you would like changed?

**Comment by EricChen1248** [comment]
Nothing as of right now. I haven't gotten around to properly using it. Am waiting for the new semester to start before I'll have enough things to keep track. But this looks program looks very promising.

**Comment by Jemoka** [comment]
Closed by #136
