### ISSUE TITLE
FEAT completeable projects

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#131]
**Is your feature request related to a problem? Please describe.**
Projects don't disappear when its contents are all completed.

**Describe the solution you'd like**
Being able to do so, perhaps as a toggle.

**Additional context**
A la OmniFocus, from [quantumish#3800](https://discordapp.com/channels/691409213653778444/723796928739016704/737695167678644264)

**Comment by richardfeynmanrocks** [comment]
@Jemoka To clarify a little more, I care less about batch completion and more about having projects disappear when marked as completed so that they don't linger as empty shells forever.

**Comment by Jemoka** [comment]
ok, updated the issue! Thanks! @richardfeynmanrocks

**Comment by Jemoka** [comment]
1+ from an user email. Bump.

**Comment by Jemoka** [comment]
And finally, @TheEnquirer did it on #178. Closing.

**Comment by Jemoka** [comment]
the PR is apparently not merged yet; reopening.

**Comment by Jemoka** [comment]
Ok, merged! Tada!

**Comment by Jemoka** [comment]
@richardfeynmanrocks be happy now.
