### ISSUE TITLE
FEAT Data accessing (ideally with something akin to an API)

### ISSUE THREAD

**Issue by richardfeynmanrocks** [Shabang-Systems/Condution#135]
**Is your feature request related to a problem? Please describe.**
It's rather frustrating that it's impossible to get my data outside of Condution without building my own Condution + backend (and there's no method of copying or exporting projects/tasks/perspectives to a version built from source so that doesn't even work as a solution...) 

**Describe the solution you'd like**
Ideally, some sort of API that I could call (hopefully not only JS) or HTTP request I could make that would get me a list of tasks + associated data (part of which project, which tags, due date, defer date, etc...). 

However, any way will work. For example, a button for exporting data to a file or offline support's local storage being scrapable and not some binary would both do the trick (albeit a little less conveniently).

**Additional context**
#55 seems to briefly mention this but I think this request is a little different in scope.

This would drastically improve the quality of this app in my opinion, as combined with the open-source nature of Condution, it would allow for significantly increased customizability + scriptability (OF only ever had a weird AppleScript system for things like accesses).

**Comment by Jemoka** [comment]
Closing in favor of #88 which, upon closing, promises a docker container + an API that you could host.
