### ISSUE TITLE
BUG-unconfirmed-due-dates

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#140]
**Describe the bug**
Typing in a due date with NLP then clicking away updates due date but not checkbox color.

**To Reproduce**
1. Create a task
2. Input a duedate that would change checkbox color, like `this evening`
3. Without pressing enter, click out of the task
4. Re-enter the task. See that a due date is set but the checkbox color is not changed.

**Expected behavior**
Either change both or change neither (I vote both)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Condution
 - Version: beta-v0.2.3_build1_M

**Comment by Jemoka** [comment]
k will investigate

**Comment by Exr0n** [comment]
@Jemoka this is related to #126 btw, so you should probably take a look at that while fixing this :)

**Comment by Jemoka** [comment]
Closing in favor of #141
