### ISSUE TITLE
BUG jquery timepicker addon woes

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#141]
**Describe the bug**
#106 #140 #126 #142

Master thread talking about alternative date pickers, or otherwise making the current one better.

**Comment by Exr0n** [comment]
@Jemoka is this about alternatives or debugging the current system?

**Comment by Exr0n** [comment]
Should also add #142 to the list I guess

**Comment by Jemoka** [comment]
> @Jemoka is this about alternatives or debugging the current system?

Both. Our current system is not quite mobile friendly either, so I have been brooding over replacing it. 

Thinking about something in either Aqualand or Materialand. jQuertland just doesn't offer the mobility

**Comment by Jemoka** [comment]
closed by 1.0
