### ISSUE TITLE
BUG-nlp-time-default-after

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#142]
**Describe the bug**
NLP due date/time processing defaults to the first available option in the current "logical block", but often not what I actually want. For example, typing 'Thursday' on a Friday will set the time to be the day before, not the Thursday after. Same with times: `3:50` becomes 3:50 AM instead of 3:50 in the afternoon.

**To Reproduce**
1. Open the add button to inbox button
2. Type a task and date/time that has already passed

**Expected behavior**
Choose the closest date/time that hasn't happened yet.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Condution
 - Version: beta-v0.2.3_build1_M

**Additional context**
Also mentioned by @quantumish

**Comment by Jemoka** [comment]
Closing in favor of #141
