### ISSUE TITLE
BUG Big Sur app corner whiteness

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#143]
**Describe the bug**
App border radius causes problems in macOS Big Sur. See this:
<img width="50" alt="Screen Shot 2020-07-31 at 4 55 59 PM" src="https://user-images.githubusercontent.com/28765741/89088776-df91b700-d34e-11ea-8fc9-23641f6a6729.png">
Notice how the corners are white instead of #f4f4f4. 

**To Reproduce**
1. Open the app in macOS BS

**Expected behavior**
No colorful corners, also rounded corners.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.0 Beta (20A5323l)
 - Browser: Condution
 - Version: beta-v0.2.3beta.1

**Additional context**
Slack has the same problem, although more obviously:
<img width="76" alt="Screen Shot 2020-07-31 at 4 58 08 PM" src="https://user-images.githubusercontent.com/28765741/89088797-03ed9380-d34f-11ea-8fb1-792b9681798e.png">
Discord, however, solves this. What I guess is happening is that they have window border: transparent in their main.js.
<img width="78" alt="Screen Shot 2020-07-31 at 5 00 02 PM" src="https://user-images.githubusercontent.com/28765741/89088852-529b2d80-d34f-11ea-87ef-88418333118b.png">
Spark averts this, but ends up causing another problem somehow with the edge not aligning. We used to have this issue but I don't think this applies anymore.
<img width="73" alt="Screen Shot 2020-07-31 at 5 00 36 PM" src="https://user-images.githubusercontent.com/28765741/89088877-71012900-d34f-11ea-9dc6-cd1a33e33ab4.png">

**Comment by Jemoka** [comment]
@Exr0n — sorry for assigning ya, but currently the two of us are running macOS BS, so we could cross-check.

**Comment by Jemoka** [comment]
Goining into 080 because BS' not getting release for another long time.

**Comment by Exr0n** [comment]
I’m actually not on Big Sur anymore after those boot shenanigans. And I think I’m staying away from MacOS betas from now on.

**Comment by Jemoka** [comment]
Oh oh why did you leave Big Sur?

**Comment by Jemoka** [comment]
Fixed by fcd794b. That was quick.

**Comment by Jemoka** [comment]
Repoening because `1.0.0` and above breaks again? IDK if that's actually true, though.

**Comment by Exr0n** [comment]
I am infact no longer on macOS (mostly). so no, sorry.

**Comment by Jemoka** [comment]
the task: find non-linux people on this team.

**Comment by Jemoka** [comment]
No longer! I am on an apple m1 big sur and its fine now. Closing.

**Comment by Jemoka** [comment]
<img width="115" alt="Screen Shot 2021-08-24 at 6 42 48 PM" src="https://user-images.githubusercontent.com/28765741/130712449-ae215e5c-c031-41e7-a1a3-1e1356c63310.png">
pretty corners 😍
