### ISSUE TITLE
FEAT MultiFactor Auth

### ISSUE THREAD

**Issue by Ban-Ironic-Ohms** [Shabang-Systems/Condution#146]
**Describe the solution you'd like**
An option to enable multi factor authentication with a sms code or auth app code

**Comment by Jemoka** [comment]
Later, but there should be a "fix everything with auth now quickly go!" issue including
1. #146
2. #109 
3. #167

**Comment by Jemoka** [comment]
this will be possibe with Supabase stack, but I don't think we should support this with Firebase.
