### ISSUE TITLE
FEAT Teams

### ISSUE THREAD

**Issue by Ban-Ironic-Ohms** [Shabang-Systems/Condution#150]
**Is your feature request related to a problem? Please describe.**
Large scale sharing across a team

**Describe the solution you'd like**
Team/enterprises accounts that function as a shared account, though with different team roles (team lead, manager, member).

**Additional context**
Long term solution, but it would be helpful. This is a 1.0.0 stage feature

**Comment by Jemoka** [comment]
Not a wish anymore! Closed by 1.0
