### ISSUE TITLE
FEAT Local backup of online account data

### ISSUE THREAD

**Issue by VegaDeftwing** [Shabang-Systems/Condution#160]
Had a brief time when I couldn't login, so I couldn't access my data. Having the ability to at least have a local backup of my data would make me significantly more comfortable using condution, especially as the program/app is still new.

It would be nice if each of the desktop clients (Mac, Windows, Linux) stored a local copy of the task list *somewhere*. On Linux with the appimage this is obviously a bit clunky, but I think it's necessary regardless.

Preferably, the file would be saved in a format that is both computer and human readable, maybe just
```
projectName:task:description:start:end
```
of course, this is only an example, whatever the separation character it'd likely need to be something that is *invalid* for input in the actual gui, to make parsing easy.

**Comment by trif55** [comment]
I was just thinking this as well, also what back end is currently used for online sync? I only ask as I'm surprised a free application pays for the hosting of everyone's tasks centrally, I expected a requirement for google drive or something for sync

**Comment by VegaDeftwing** [comment]
The issue caused me to move to something else (in my case https://github.com/SolarLune/masterplan, I'll use either git or Syncthing for sync) because I just don't trust that I won't lose my data for exactly what trif is saying. It really sucks though, because I think Condution had some really nice things going on- But I can't even recommend this to friends with this as an outstanding issue.

**Comment by Jemoka** [comment]
Uhmmm... For your case, does offline mode work for you? We store your tasks in that case in a JSON tree as part of AppData, but then you would loose the functionality of sync if you opt for that option.
Happy to have an option to write to a JSON anyways, which... should? be pretty easy to do. We are working on a major update soon, and so stay tuned for more info on that end. 

Let me know if this helps!

**Comment by Jemoka** [comment]
> I was just thinking this as well, also what back end is currently used for online sync? I only ask as I'm surprised a free application pays for the hosting of everyone's tasks centrally, I expected a requirement for google drive or something for sync

Our backend on the deploy binaries are Google's Firebase, which usually works pretty well. We pay for people's databases by having patrons ;) — https://www.patreon.com/condution.

**Comment by jcz1** [comment]
http://todotxt.org is great format for ToDos.
Anyway, data at Google is not an option for me :-(

**Comment by Jemoka** [comment]
No worries! Our offline mode ("use on your device") does not touch Google at all, and simply stores data on a JSON in AppData.

**Comment by Jemoka** [comment]
Backend changes are done to allow this, but #55 will need to happen for this.

**Comment by VegaDeftwing** [comment]
This is also less relevant if, as per the latest release notes, it is possible to self host. Still, glad to see progress is being made!

**Comment by VegaDeftwing** [comment]
🎉 Props on getting a 2 year issues resolved. Always feels good to get those off the issue tracker.
