### ISSUE TITLE
FEAT Markdown Support for Task Descriptions & Titles

### ISSUE THREAD

**Issue by DrBoklan** [Shabang-Systems/Condution#181]
**Is your feature request related to a problem? Please describe.**
I'd like support for clickable links/URL's in tasks.

**Describe the solution you'd like**

Markdown styled URL support in Task Titles, when text is clicked, open it in default browser

`[Task](http://someonlineresource)`

**Comment by Jemoka** [comment]
Also, expansion for Markdown full support in task Description, and titles. Make'em bigger too!

**Comment by Jemoka** [comment]
Closed by #223
