### ISSUE TITLE
BUG Cannot add tag if all tags removed

### ISSUE THREAD

**Issue by C-J1** [Shabang-Systems/Condution#194]
**Describe the bug**
If you have removed all the tags for some reason, the "add tag" option goes away.

**To Reproduce**
1. Go to any task
2. Click on 'Tags'
3. Remove all tags
4. No "Add tag" option
5. Close tags modal
6. Re-open modal, still no add tags

**Expected behavior**
Add tag option remains all the time.

**Desktop (please complete the following information):**
 - Browser: Brave (not sure how to see version)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 11
 - Version: v1.0.2

**Additional context**
I had a look in the dev tools in Brave. I can't see a button that has been hidden and not toggled.

**Comment by Jemoka** [comment]
@zbuster05 zaaaaach? Could you check if tags pane does has a css/actual UI issue?

**Comment by Jemoka** [comment]
@zbuster05 any headway?

**Comment by Jemoka** [comment]
Fixed by #203
