### ISSUE TITLE
BUG Text in "Condution Yourself" needs updating to reflect UI

### ISSUE THREAD

**Issue by TheDowdy** [Shabang-Systems/Condution#195]
**Describe the bug**
Quite a minor bug and a quick fix — The "Condution Yourself" tutorial project says to tap the three vertical dots, but after some searching I found the button is actually a vertical/horizontal arrowed line toggle. Presumably the UI was tweaked but the text remains the same in Condution Yourself.

**To Reproduce**
1. In Condution app on macOs, go to 'Condution Yourself' tutorial project.
2. See the "Tap the three vertical dots ↗" text, but no vertical dots on UI.

**Expected behavior**
The text should refer to the actual button that is there now.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: v1.0.2_build0_M

**Additional context**
Thanks for what looks like a great tool!

**Comment by Jemoka** [comment]
@zbuster05 onboarding english localization sadness!

**Comment by Ban-Ironic-Ohms** [comment]
Closed with commit
needsLOC

**Comment by Jemoka** [comment]
@Ban-Ironic-Ohms post the commit hash here? Merge to 1.0.3

**Comment by Ban-Ironic-Ohms** [comment]
hash: c4f806aa3b0ccf2348db4a5a5dd186543ca77299
