### ISSUE TITLE
FEAT settings page

### ISSUE THREAD

**Issue by zbuster05** [Shabang-Systems/Condution#55]
**Is your feature request related to a problem? Please describe.**
Adding user preferences page.

**Comment by Ban-Ironic-Ohms** [comment]
Also, as more and more features are added, they should be toggl-able, like time tracking (pun intended).

Project sharing should be handled from there, and password reset.

**Comment by Jemoka** [comment]
> Also, as more and more features are added, they should be toggl-able, like time tracking (pun intended).
> 
> Project sharing should be handled from there, and password reset.

Friendly ping @zbuster05

**Comment by Jemoka** [comment]
Oh lord @zbuster05 this was the thing you need to work on!

**Comment by Jemoka** [comment]
@TheEnquirer @FlyN-Nick let's focus on this as soon as 1.1 + 1.1.1 gets merged.

**Comment by Jemoka** [comment]
also from user email — the ability to direct the theme in settings page. @TheEnquirer has mentioned this too. Bump!

**Comment by Jemoka** [comment]
Closes by #266
