### ISSUE TITLE
Reactify master thread

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#60]
There has been talks around the team regarding Reactifying Condution. This is a place where you could have that kind of discussion, and more! 

Not a bug. Not a feature. Just a discussion! @Shabang-Systems/teamcondution

**Comment by Exr0n** [comment]
Can we don't?
It feels like we've had bad experiences with it in the past.

**Comment by Jemoka** [comment]
Yes, but also. `states`

**Comment by Ban-Ironic-Ohms** [comment]
Closing old issues: this was done! Much better (I hope)
