### ISSUE TITLE
Uncompleting Tasks is Glitchy

### ISSUE THREAD

**Issue by Exr0n** [Shabang-Systems/Condution#78]
**Describe the bug**
Uncompleting tasks in the task menu is glitchy--tasks disappear, reappear, ghost around, swap places, and duplicate all on their own.

**To Reproduce**
1. Go to 'Completed'
2. Click on any of the checkboxes to uncomplete the task.
3. Await glitchyness, or repeat if 404 glitchyness not found.

**Expected behavior**
Tasks reappear in their expected places, as if a new task with the same details had just been added with orange bar. (Or other behavior, discuss below)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Uh, the Condution desktop app
 - Version: 6e55b7ee85b857d240d06f6247d5430ef7ef0d4e (HEAD -> dev-offline, origin/dev-offline)

**Additional context**
We really need to improve the bug/feature templates.

**Comment by Jemoka** [comment]
Can't reproduce. Could @Exr0n clarify?

**Comment by Jemoka** [comment]
k still can't quite reproduce. Lemme pull a #wontfix on that one until it occurs again. Maybe #65 fixed it.

**Comment by Jemoka** [comment]
Open it whence you experience again @Exr0n
