### ISSUE TITLE
BUG ship font-awesome locally

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#85]
**Describe the bug**
When users' connections are flickering, there should be local copies of fa-vectors.

**To Reproduce**
Go online. then offline. then online. then offline. etc. etc. until none of the Fa images load.

**Expected behavior**
Fa images load.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11
 - Version: bebc6d8

**Additional context**
@Ban-Ironic-Ohms

**Comment by Ban-Ironic-Ohms** [comment]
This bug was also present on iPhone 8 iOS 13.5.1

It does not show name or any tasks either

**Comment by Exr0n** [comment]
And i oop

**Comment by Jemoka** [comment]
This should be part of #74
