### ISSUE TITLE
FEAT date displays from Europe style => American Style

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#87]
**Is your feature request related to a problem? Please describe.**
Not a problem. Just a UX+QOL.

**Describe the solution you'd like**
Changing the thing on the top from 17 July 2020 => July 17th, 2020.

**Additional context**
From [this Reddit discussion](https://www.reddit.com/r/androidapps/comments/hy7ich/free_opensource_and_beautiful_productivity_app/fzbgzao?utm_source=share&utm_medium=web2x)

**Comment by Jemoka** [comment]
#55 @zbuster05 maybe this could be a toggle

**Comment by xavdid** [comment]
JS has a builtin for this that you can probably access in electron: `Date.toLocaleString` ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)). Using that will give you a good default, but you can also easily provide a user setting that feeds different values into this function.

**Comment by Exr0n** [comment]
[+1 on by Albertosaurusrex#6080](https://discordapp.com/channels/691409213653778444/723780625097556029/737416285234921543)

**Comment by Jemoka** [comment]
#190
