### ISSUE TITLE
FEAT hard storage

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#88]
**Is your feature request related to a problem? Please describe.**
Some people don't want/can't share their tasks over the interwebitubes.

**Describe the solution you'd like**
Docker container/other self-hosted way of storing tasks. Or even locally ;)

**Comment by Exr0n** [comment]
Easiest way might be to just store a serialized version of the cache in a file. I can do this if you figure out how to open and write storage files @Jemoka

**Comment by Jemoka** [comment]
easy. Use indexedDB https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API, or, easier, https://capacitorjs.com/docs/apis/storage — but the latter should be JSON only, and NO NUMBERS. Otherwise you will create #99 again.

**Comment by Jemoka** [comment]
EXTREMELY POPULAR

**Comment by Jemoka** [comment]
Ok. Docker container's not a thing yet, but the core feature is addressed by 1c7ecb9. Closing this one, and deferring docker sync feature request to its very own: #147
