### ISSUE TITLE
BUG Android Back Button does not work as expected

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#91]
**Describe the bug**
Users expect pagination to go back when, well, the back button is hit. If that it is hit on the home page, it should exit the app.

**To Reproduce**
1. Use android
2. Hit the back button

**Expected behavior**
If in a modal, exit the modal. If in a subproject, exit the subproject. If in home page, exit the app.

**Smartphone (please complete the following information):**
 - OS: Android
 - Version: bebc6d8

**Comment by Exr0n** [comment]
Superset of #96

**Comment by Jemoka** [comment]
Closed by #148
