### ISSUE TITLE
FEAT other android stores

### ISSUE THREAD

**Issue by Jemoka** [Shabang-Systems/Condution#92]
**Is your feature request related to a problem? Please describe.**
Could we upload to other android stores? Makes non-google people be able to access it.

**Describe the solution you'd like**
ibid

**Comment by Ban-Ironic-Ohms** [comment]
Working on Samsung Galaxy Apps store right now, hopefully set up in a few hours.

**Comment by Ban-Ironic-Ohms** [comment]
We are under review in the Samsung App Store! If there are more stores, feel free to re-open the issue!

**Comment by Jemoka** [comment]
Well there are still others, but let's keep this issue open in case people want to pitch in...

**Comment by Ban-Ironic-Ohms** [comment]
Closing out old issues: we are on Huawai, Amazon, and Samsung. That should cover them all, and if not, well 🤷
