### ISSUE TITLE
BUG cannot close/exit app using the back button

### ISSUE THREAD

**Issue by anonymous-user** [Shabang-Systems/Condution#96]
**Describe the bug**

Cannot exit app using back button.

**To Reproduce**

1. Open app
2. Click back button
3. App does not respond

**Expected behavior**

App should close/exit. Maybe have a prompt to do so.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Version 0.2.2

**Additional context**
I am currently using the three button navigation on my phone. I have not tested this using the gesture navigation.

**Comment by Jemoka** [comment]
Dup! Thanks for the 1+ on that feature. Please refer to #91 for progress!

**Comment by Jemoka** [comment]
Dup! Thanks for the 1+ on that feature. Please refer to #91 for progress!
