### ISSUE TITLE
BUG app keeps repeating setup process

### ISSUE THREAD

**Issue by anonymous-user** [Shabang-Systems/Condution#98]
**Describe the bug**

During first launch of the app, it goes though the setup process and brings you to the main screen. If you exit the app, it will forget everything and go through the setup process again as if new.

**To Reproduce**
1. Launch app
2. Go through setup steps
3. Close app and relaunch it
4. Repeat 2

**Expected behavior**

The app should remember its settings and state and not act like I just installed it.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Version 0.2.2

Here is a video showing what happens:

https://photos.app.goo.gl/xNtwT2JJQCAVKsH2A

**Comment by Exr0n** [comment]
@Jemoka this was fixed right? Link/merge relevant PR?

**Comment by Ban-Ironic-Ohms** [comment]
Fixed in 0.2.3 build1
